### PR TITLE
Shutup and take my custom uniforms

### PR DESCRIPTION
**Pull request by rre36**
_**Before ya' doing anything stupid, take these.**_

### CODE REVIEW

**Comment by EternalMC** [comment]
that upVectorView is computed inefficiently (you could just use gbufferModelView[1].xyz instead), and all of those uniforms are flat out wrong in skybasic and shadow. or at least, they're a frame behind what they should be. see gbuffers_skybasic.vsh in QOL for more info on how to calculate them correctly. 

Shamelessly copy pasted from discord.

**Comment by EternalMC** [comment]
Well I guess I'll take it

**Comment by rre36** [comment]
Now gib webhook in discord

**Comment by EternalMC** [comment]
@rre36 webhook made and is working

**Pull request merged**
